Update genMakefile.tcl to avoid conflicting access
When I try to compile Delphes originally, I get this error message:

error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access
       struct __xfer_bufptrs

Making the changes in this proposal gets rid of those errors.